import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { getUserDetails } from "../actions/get-user-details";


const myPoppins = Poppins({
  subsets: ['latin'],
  weight: ["400", "600", "700"]
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { data } = await getUserDetails();
  console.log(data);
  return (
    <html lang="pt-BR">
      <body
        className={`${myPoppins.className} antialiased`}
      >
        <div className="flex flex-col min-h-screen md:min-h-[calc(100vh + 10rem)]">
          <Header data={data} />
          <main className="flex-1">
            {children}
          </main>
          <Footer />
        </div>

      </body>
    </html>
  );
}
